dotsync auto-commit (2021-03-04 07:05:13)

diff --git a/tmux/tmux/bin/vmux b/tmux/tmux/bin/vmux
--- a/tmux/tmux/bin/vmux
+++ b/tmux/tmux/bin/vmux
@@ -1,83 +1,159 @@
-#!/bin/bash
-
-usage() {
-    echo "$0 [ -r ] [ -s session-name ] [ ssh-host ]"
-    exit 1
-}
+#!/usr/bin/env bash
 
 DIR="$(cd "$( dirname "${BASH_SOURCE[0]}"  )" >/dev/null 2>&1 && pwd)"
 
-run="~/.tmux/bin/mrun"
+VRUN="~/.tmux/bin/mrun"
+VMUX="~/.tmux/bin/vmux"
 
-session="mux/$(whoami)/$(hostname)"
-
-parse_host() {
-    host="$1"
-    rem_username=$(ssh -G "$host" | grep '^user ' | awk '{print $2}')
-    rem_hostname=$(ssh -G "$host" | grep '^hostname ' | awk '{print $2}')
-    rem_hostname=$(echo "$rem_hostname" | sed -nr 's|(.*\.)*(.+)\.[[:alnum:]]+$|\2|p')
-    rem_session="r/$session/$rem_username/$rem_hostname"
-    echo "$rem_session"
+function usage
+{
+    echo "$0 [-r] [-n] [-h] -s session-name [ssh-host]"
+    echo "  -r remove session"
+    echo "  -n do not automatically add user and hostname to the session name"
+    echo "  -h print this help"
+    exit 1
 }
 
-main() {
-    while getopts ":hs:" opt; do
+function remove
+{
+    if [[ -n "$HOST" ]]; then
+        SESSION=$(parse_host)
+        if tmux has-session -t "$SESSION" &>/dev/null; then
+            tmux kill-session -t "$SESSION"
+        else
+            echo "No local session '$SESSION' could be found."
+            exit 1
+        fi
+        if ssh -t $HOST tmux has-session -t "$SESSION" &>/dev/null; then
+            ssh -t $HOST tmux kill-session -t "$SESSION"
+            echo "No remote session '$SESSION' could be found."
+            exit 1
+        fi
+    else
+        if [[ -z "$NORENAME" ]]; then
+            SESSION="$SESSION/$(whoami)/$(hostname)"
+        fi
+        if tmux has-session -t "$SESSION" &>/dev/null; then
+            tmux kill-session -t "$SESSION"
+        else
+            echo "No local session '$SESSION' could be found."
+            exit 1
+        fi
+    fi
+    exit 0
+}
+
+function parse_host
+{
+    if ! grep -i "^Host $HOST\$" ~/.ssh/config &>/dev/null; then
+        echo "Provided host '$HOST' cannot be found in ssh config file."
+        echo "Please change your ssh config file accordingly."
+        exit 1
+    else
+        USER=$(ssh -G "$HOST" | grep '^user ' | awk '{print $2}')
+    fi
+    echo "$SESSION/$USER/$HOST"
+}
+
+function lvmux
+{
+    if [[ -z "$NORENAME" ]]; then
+        SESSION="$SESSION/$(whoami)/$(hostname)"
+    fi
+
+    if tmux has-session -t "$SESSION" &>/dev/null ; then
+        if [[ -z "$TMUX" ]]; then
+            eval $PRE exec tmux attach-session -t "$SESSION"
+        else
+            echo "Session '$SESSION' is in detached mode. Unset \$TMUX."
+            exit 1
+        fi
+    else
+        tmux new-session -d -s "$SESSION"
+        if [[ -z "$TMUX" ]]; then
+            eval $PRE exec tmux attach-session -t "$SESSION"
+        else
+            echo "Session '$SESSION' is in detached mode. Unset \$TMUX."
+            exit 1
+        fi
+    fi
+}
+
+function rvmux
+{
+
+    SESSION=$(parse_host)
+    local remcmd="$VMUX -ns $SESSION"
+    local sshcmd="ssh -t $HOST $remcmd"
+
+    if tmux has-session -t "$SESSION" &>/dev/null; then
+        if [[ -z "$TMUX" ]]; then
+            eval $PRE exec tmux attach-session -t "$SESSION"
+        else
+            echo "Session '$SESSION' is in detached mode. Unset \$TMUX."
+            exit 1
+        fi
+    else
+        tmux new-session -d -s "$SESSION" "$sshcmd"
+        tmux run "$VRUN switch_sendkeys_mode"
+        if [[ -z "$TMUX" ]]; then
+            eval $PRE exec tmux attach-session -t "$SESSION"
+        else
+            echo "Session '$SESSION' is in detached mode. Unset \$TMUX."
+            exit 1
+        fi
+    fi
+}
+
+function main
+{
+    while getopts ":hnrs:" opt; do
         case $opt in
-            s)
-                session="$OPTARG"
-                ;;
             h)
                 usage
                 ;;
+            n)
+                NORENAME=1
+                ;;
             r)
-                remove=1
+                REMOVE=1
+                ;;
+            s)
+                SESSION="$OPTARG"
                 ;;
             \?)
-                echo "Invalid option: $OPTARG" 1>&2
+                echo "Invalid option: $OPTARG." 1>&2
                 usage
                 ;;
             :)
-                echo "Invalid option: $OPTARG requires an argument" 1>&2
+                echo "Invalid option: $OPTARG requires an argument." 1>&2
                 usage
                 ;;
         esac
     done
     shift $((OPTIND - 1))
 
+    if [[ -z "$SESSION" ]]; then
+        echo "Missing mandatory session name." 1>&2
+        usage
+    fi
+
+    HOST="$1"
+
+    if [[ -n "$REMOVE" ]]; then
+        remove
+    fi
+
     if [[ "$TERM" = linux  && $(tty) =~ /dev/pts/.* ]]; then
         PRE='TERM=fbterm'
     fi
 
-    local host="$1"
-    if [[ -z "$host" ]]; then
+    if [[ -z "$HOST" ]]; then
         lvmux
     else
-        session=$(parse_host "$host")
         rvmux
     fi
     exit 0
-}
-
-lvmux() {
-    if tmux has-session -t "$session" &>/dev/null ; then
-        eval $PRE exec tmux attach-session -t "$session"
-    else
-        eval $PRE exec tmux new-session -s "$session"
-    fi
-}
-
-rvmux() {
-    remcmd="~/.tmux/bin/vmux -s $session"
-
-    sshcmd="ssh -t $host $remcmd"
-
-    if tmux has-session -t "$session" &>/dev/null; then
-        exec tmux attach-session -t "$session"
-    else
-        tmux new-session -d -s "$session" "$sshcmd"
-        tmux run "$run switch_sendkeys_mode"
-        exec tmux attach-session -t "$session"
-    fi
 }
 
 main "$@"
